pipelineJob("Cart-CI") {
  description('CIJOB Cart Service')
  definition {
    cpsScm {
      scm {
        git {
          remote {
            url("https://github.com/learn2earnSRK/DevopsLearnings.git")
          }
          branch("*/master")
        }
      }
      scriptPath("Jenkinsfile")
    }
  }
}

pipelineJob("Catalogue-CI") {
  description('CIJOB Catalogue Service')
  definition {
    cpsScm {
      scm {
        git {
          remote {
            url("https://github.com/learn2earnSRK/DevopsLearnings.git")
          }
          branch("*/master")
        }
      }
      scriptPath("Jenkinsfile")
    }
  }
}

pipelineJob("Userr-CI") {
  description('CIJOB User Service')
  definition {
    cpsScm {
      scm {
        git {
          remote {
            url("https://github.com/learn2earnSRK/DevopsLearnings.git")
          }
          branch("*/master")
        }
      }
      scriptPath("Jenkinsfile")
    }
  }
}
