pipeline {
agent {
      label 'CI'
      }
      
      environment {
            APP_VERSION = '1.0'
                }
      
          stages{
                
                environment {
                  APP_VERSION = '2.0'
                }
                     
            stage ('Testing') {
               steps {
                    sh 'env'
                    }
                }
            }
        }
    
    
    
    
