pipeline {
agent {
      label 'CI'
      }
      
      environment {
            APP_VERSION = '1.0'
            SSH = credentials ('SSH-CENTOS-INFRAA')
                }
      
          stages{      
            stage ('Stage-1') {
               environment {
                  APP_VERSION = '2.0'
                       }
                         steps {
                               sh 'env'
                    }
                }
            }
        }
    
    
    
    
